### ISSUE TITLE
screenshot highlight area offset

### ISSUE THREAD

**Issue by hakkurishian** [RickonChen/feedback#2]
Great that the module is now working on Angular6. However, I'm facing an issue on Google Chrome and Safari with the Overlay for highlighting parts of the image. While it displays everything correctly while drawing the yellow rect and also it shows the right image in the preview, the final image is widely offset and the covering layer seems way too small:

<img width="366" alt="screenshot 2018-10-16 at 10 20 41" src="https://user-images.githubusercontent.com/6708117/47002618-c85be800-d12d-11e8-9777-b409d480d99d.png">
<img width="1639" alt="screenshot 2018-10-16 at 10 23 32" src="https://user-images.githubusercontent.com/6708117/47002637-d447aa00-d12d-11e8-83b0-d81d0c89e374.png">

What are possible reasons for this ?

**Comment by RickonChen** [comment]
Hi @hakkurishian , actually current way to draw rectangle is not the best. The project is being updated for using a new way to draw rectangle. Once it done, the issue you met should be fixed. I reckon the update will be completed around two weeks.

**Comment by hakkurishian** [comment]
Hi @RickonChen - is there any update on this? I'd be willing to help if that makes sense at this stage.

**Comment by RickonChen** [comment]
Hi @hakkurishian , yes. The update should could be finished before next Tuesday.

**Comment by hakkurishian** [comment]
Hi @RickonChen  thank you ! Now the last problem I'm facing regarding the screenshot is that the little toolbar is not draggable if it is below the highlighted rect( which can be resolved by moving it away before highlighting)

**Comment by RickonChen** [comment]
Hi @hakkurishian , the issue seems could be solved by adjusting the z-index of rectangles and toolbar. I will see if I can fixed duing this week.

**Comment by RickonChen** [comment]
Hi @hakkurishian, latest version 1.1.5 or newer has solve the issue.
