### ISSUE TITLE
Custom discription template

### ISSUE THREAD

**Issue by eyalerez1** [RickonChen/feedback#3]
Hi,

First of all, I want to say thank you and very well done for an excellent project!
I embedded it easily and it works as expected.

I have only one question, is it possible to display a template in the description for the user to fill? Currently, there is an autofocus to the description field so the placeholder ("Describe your issue or share your ideas") display only for a split second.

Thanks!

**Comment by eyalerez1** [comment]
Update:
"Currently, there is an autofocus to the description field so the placeholder ("Describe your issue or share your ideas") display only for a split second."

That was my bug...

So my only question is if its possible to have custom descriptionTips.

Thanks!

**Comment by RickonChen** [comment]
Hi @eyalerez1 , sure. Custom message such like placeholder or button text are being  added. It should could be finish before next Wednesday.

**Comment by eyalerez1** [comment]
Thanks!
I think it would also be nice to have an option for a template (instead of a placeholder), which is actually an initial description.
Thank you again for your great work!

**Comment by RickonChen** [comment]
Hi @eyalerez1 , haha. Thanks. BTW, a brand new way to draw rectangle is introduced in the newest version. You may update you package to try the new feature.

**Comment by eyalerez1** [comment]
Hi,
Any updates?

Thanks!

**Comment by RickonChen** [comment]
Hi @eyalerez1 , 1.1.6 or newer should fulfill your need.

**Comment by eyalerez1** [comment]
Thank you again for the great work!
