### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by hakkurishian** [RickonChen/feedback#4]
Since the last Version the file feedback.service.d.ts causes build errors on angular CLI 6.

`ERROR in node_modules/ng-feedback/lib/feedback.service.d.ts(3,30): error TS1005: ';' expected.
node_modules/ng-feedback/lib/feedback.service.d.ts(3,96): error TS1005: '(' expected.
node_modules/ng-feedback/lib/feedback.service.d.ts(4,5): error TS1128: Declaration or statement expected.
node_modules/ng-feedback/lib/feedback.service.d.ts(5,87): error TS1005: '(' expected.
node_modules/ng-feedback/lib/feedback.service.d.ts(6,27): error TS1005: ';' expected.
node_modules/ng-feedback/lib/feedback.service.d.ts(6,33): error TS1109: Expression expected.
node_modules/ng-feedback/lib/feedback.service.d.ts(7,5): error TS1128: Declaration or statement expected.
node_modules/ng-feedback/lib/feedback.service.d.ts(8,21): error TS1005: ',' expected.
node_modules/ng-feedback/lib/feedback.service.d.ts(8,27): error TS1005: ';' expected.
node_modules/ng-feedback/lib/feedback.service.d.ts(8,33): error TS1109: Expression expected.
node_modules/ng-feedback/lib/feedback.service.d.ts(9,25): error TS1005: ',' expected.
node_modules/ng-feedback/lib/feedback.service.d.ts(9,31): error TS1005: ';' expected.
node_modules/ng-feedback/lib/feedback.service.d.ts(9,37): error TS1109: Expression expected.
node_modules/ng-feedback/lib/feedback.service.d.ts(10,21): error TS1005: ',' expected.
node_modules/ng-feedback/lib/feedback.service.d.ts(10,27): error TS1005: ';' expected.
node_modules/ng-feedback/lib/feedback.service.d.ts(11,1): error TS1128: Declaration or statement expected.
` 

**Proposed Solution**

I got it working after replacing the Rxjs related imports by 

`import {Observable} from "rxjs/Rx";`

this is what my working file looks like:

`import {Observable} from "rxjs/Rx";

export declare class FeedbackService {
    private screenshotCanvasSource;
    screenshotCanvas$:Observable<any>;
    private feedbackSource;
    feedback$: Observable<{}>;
    initScreenshotCanvas(): void;
    private generateExistingCanvas;
    setCanvas(canvas: any): void;
    setFeedback(feedback: any): void;
    getImgEle(canvas: any): HTMLImageElement;
}
`

**Comment by RickonChen** [comment]
Hi @hakkurishian , it do work! Actually I had to manually to update the feedback.service.d.ts each time after building. I have updated code and published new viersion to npm. Thanks for providing the solution!
