### ISSUE TITLE
After open of the feedback dialog, background of other layered component is invisible.

### ISSUE THREAD

**Issue by reyzenkind** [RickonChen/feedback#5]
After open of the feedback dialog, background of other layered component is invisible.

Other layered component use also div with css class .mat-dialog-container. 
feedback-dialog component set "mat-dialog-container" invisible.

https://github.com/RickonChen/feedback/blob/190e9fb6e5ddaa2fab372fbf3cb9a6d0e041e661/src/app/feedback/feedback-dialog/feedback-dialog.component.css

/deep/ .mat-dialog-container {
  padding: 0;
  overflow: visible;
  background-color: rgba(255, 255, 255, 0);
  box-shadow: initial;
}

Expected: after closing feedback-dialog , component restore default css for .mat-dialog-container

**Comment by RickonChen** [comment]
Hi @reyzenkind , version 1.1.8 or newer should fix the issue you met
