### ISSUE TITLE
Errors when using 'Include screenshot' in Firefox

### ISSUE THREAD

**Issue by JoachimVeulemans** [RickonChen/feedback#6]
When using the feedback in an li-element in Firefox, some errors occur. 
`<li class="hidden-xs" feedback (send)="sendFeedback($event)"></li>`

The errors that I get are (more info in screenshots):
- Invalid value given for Length: "auto"
- ERROR DOMException: "The operation is insecure."
- ERROR TypeError: "Argument 1 of Node.appendChild is not an object."

![image](https://user-images.githubusercontent.com/32447944/53303700-013f6280-386e-11e9-8581-322ce048614b.png)

The errors only occur when I am using Firefox. They don't appear in Chrome. I'm using Angular-cli 7.3.3.

**Comment by workfel** [comment]
Hi, @JoachimVeulemans , i forked this repository because the author not maintain this one.
I solve your problem on the new npm package https://www.npmjs.com/package/ngx-md-feedback.
